data:
    path: "data/"
    mnist_path: "data/mnist"
    svhn_path: "data/svhn"
    cifar10_path: "data/cifar10"
    miniimagenet_path_train: "data/miniimagenet/train"
    miniimagenet_path_valid: "data/miniimagenet/val"
    image_size: 84
    num_workers: 6

model:
    name: "OneShotAug"
    pretrained: True
    arch: vgg16_bn #resnet,densenet
    base_width: 4 #resnet params
    cardinality: 32 # resnet params
    depth: 29
    
    z_dim: 100  # Random noise dimension coming into generator, per output vector
    real_dim: 1024  #$image_size * image_size
    channels: 3
    filters: 64
    conv1: 16
    conv2: 32
    conv3: 64
    conv4: 128
    use_dropout: True
    dropout: 0.3
    use_augmentation: True
    dataset: miniimagenet
    n_classes: 65
    #n_classes_valid: 20
    #n_classes_tets: 15

train:
    model_dir: "logs/miniimagenet"
    batch_size: 64
    train_steps: 50000
    shuffle: true
    
    d_learning_rate: 0.0002  # 2e-4
    g_learning_rate: 0.0002
    optim_betas:
        - 0.5
        - 0.999
    
    save_checkpoints_steps: 1000
    verbose_step_count: 100
    show_progrees_bar: False
predict:
    batch_size: 64

slack:
    webhook_url: ""  # after training notify you using slack-webhook
    