data:
    path: "data/"
    mnist_path: "data/mnist"
    svhn_path: "data/svhn"
    cifar10_path: "data/cifar10"
    miniimagenet_path: "data/miniimagenet"
    image_size: 224
    num_workers: 6
    channels: 3

model:
    name: "OneShotAug"
    type: "known_net"
    pretrained: True
    
    arch: vgg19_bn
    filters: 64
    transductive: True
    #    base_width: 4 #resnet params
    #    cardinality: 32 # resnet params
    #    depth: 29
    use_dropout: False
    dropout: 0.3
    dataset: miniimagenet
    #    total_train_classes: 65 #miniimagenet
    #    total_valid_classes: 20 #miniimagenet
    #    total_test_classes: 15 #miniimagenet
    n_classes: 5 # number of data classes to sample.
    num_smaples_in_shot: 1 # number of examples per data class.
    train_shot: 15
train:
    use_augmentation: False
    model_dir: "outputs/pretrained_vgg_19_aug_ae"
    batch_size: 64
    shuffle: true
    
    learning_rate: 0.001  # 2e-4
    meta_lr: 0.001
    optim_betas:
        - 0
        - 0.999
    
    
    save_checkpoints_steps: 1000
    verbose_step_count: 50
    inner_batch_size: 10 # batch size for every inner-loop training iteration.
    inner_iters: 8 #n umber of inner-loop iterations.
    replacement: False # sample with replacement.
    meta_batch_size: 5 # how many inner-loops to run
    meta_iters: 100000 # epochs
eval:
    eval_inner_iters: 50
    inner_batch_size: 5 # batch size for every inner-loop training iteration.
predict:
    use_augmentation: True
    num_sample_augmentation: 5
slack:
    webhook_url: ""  # after training notify you using slack-webhook
    