data:
    path: "data/"
    mnist_path: "data/mnist"
    svhn_path: "data/svhn"
    cifar10_path: "data/cifar10"
    miniimagenet_path: "data/miniimagenet"
    miniimagenet_path_train: "data/miniimagenet/train"
    miniimagenet_path_valid: "data/miniimagenet/val"
    image_size: 224
    num_workers: 6
    channels: 3

model:
    name: "OneShotAug"
    type: "known_net"
    pretrained: False

    arch: vgg19_bn
    
    transductive: True
    use_dropout: False
    dropout: 0.3
    dataset: miniimagenet_concat
    n_classes: 64
train:
    batch_size: 16
    use_augmentation: True
    model_dir: "outputs/train_vgg16"
    shuffle: true
    epochs: 30
    learning_rate: 0.0005
    meta_lr: 0.001
    optim_betas:
        - 0.5
        - 0.999
eval:
    use_augmentation: True
predict:
    use_augmentation: True
    num_sample_augmentation: 5
slack:
    webhook_url: ""  # after training notify you using slack-webhook
    